AWSTemplateFormatVersion: 2010-09-09
Description: Creates an IAM Execution Role for the SageMaker Notebook Instance.

Resources:
  IAMRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - sagemaker.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      RoleName: SageMaker-Notebook-Role
      Tags: 
        - Key: SageMaker-Notebook-Role
          Value: SageMaker-Notebook-Role